import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const vazirFont = localFont({
  src: [
    {
      path: "../../public/fonts/vazir/regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/vazir/medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/vazir/bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "Map App",
  description: "Generated by M. Jabbarpour",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.className} ${vazirFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
